# Generated by Django 4.2.1 on 2023-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0018_schedule_desired_aligment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="desired_aligment",
        ),
        migrations.AddField(
            model_name="schedule",
            name="alignment_offset",
            field=models.DurationField(
                blank=True,
                help_text="If alignment is enabled, offset of that alignment",
                null=True,
            ),
        ),
    ]
