# Generated by Django 4.2.1 on 2023-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0020_schedule_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="alignment_rate",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="The percetange rate at which the interval will be modified to achieve alignment.",
            ),
        ),
    ]
